---
- name: Install SELinux deps 
  yum: name=libselinux-python

- name: Disable SELinux
  selinux: state=disabled
  register: selinux_disabled

- name: Restart host
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: selinux_disabled.changed == true

- name: Wait for machine to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
  sudo: false
  when: selinux_disabled.changed == true
